theme: minima
title: Your awesome title
author: Ross Anthony Quigley
email: rossanthonyquigley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Ross Quigley, kept up for the sake of reference & proffessional correspondance

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  RossQuigley # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
